export const ACTION = {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_CART: 'CLEAR_CART',
  SET_PAY_TOKEN: 'SET_PAY_TOKEN',
  CLEAR_PAY_TOKEN: 'CLEAR_PAY_TOKEN',
  SET_BINDING_ID: 'SET_BINDING_ID',
  CLEAR_BINDING_ID: 'CLEAR_BINDING_ID',
  SET_BIND_APP_TRANS_ID: 'SET_BIND_APP_TRANS_ID',
  CLEAR_BIND_APP_TRANS_ID: 'CLEAR_BIND_APP_TRANS_ID',
  CLEAR_AGREEMENT: 'CLEAR_AGREEMENT'
}